#!/bin/bash

# Script to startup the logging service, must be run as root.
# Call it from /etc/rc.local
# David Bannon 23/9/2015

sleep 5
# This will turn both water ports off.
echo "Initializing water ports from startup script, new log, probably new boot." > /home/dbannon/logs/water.log
date >> /home/dbannon/logs/water.log
python2.7 /home/dbannon/bin/water-new.py -v -I >> /home/dbannon/logs/water.log  2>&1

RECENT="2014"
RES=`date +%Y`
FULLDATE=`date`
echo "Startup at $RES $FULLDATE" >> /home/dbannon/logs/startup.log
if [ "$RES" -lt "$RECENT" ]; then
	echo "Date ($RES) not suitably set, waiting 10 sec" >> /home/dbannon/logs/startup.log
	sleep 10
	RES=`date +%Y`
	if [ "$RES" -lt "$RECENT" ]; then
		echo "Date ($RES) not suitably set, waiting 20 sec" >> /home/dbannon/logs/startup.log
		sleep 20
		RES=`date +%Y`
		if [ "$RES" -lt "$RECENT" ]; then
			echo "Date ($RES) not suitably set, waiting 40 sec" >> /home/dbannon/logs/startup.log
			sleep 40
			RES=`date +%Y`
			if [ "$RES" -lt "$RECENT" ]; then
				echo "Date ($RES) not suitably set, exiting" >> /home/dbannon/logs/startup.log
				echo "Unable to set data $RES startup failed" >> /home/dbannon/logs/startup-ERROR.log
				exit 1
			fi
		fi
	fi
fi
sleep 10
cd /home/dbannon/http; nohup /usr/bin/python2.7 -u -m SimpleHTTPServer 8080 > /home/dbannon/logs/web.log & 
nohup /home/dbannon/bin/raspicapture -c -d /home/dbannon/http  > /home/dbannon/logs/raspicapture.log 2>&1 &

# nohup python2.7 -u /home/dbannon/bin/capture.py -w -d /home/dbannon/http/ -c > /home/dbannon/logs/capture.log 2>&1 &
# sudo -u dbannon python2.7 /home/dbannon/bin/water-new.py -v -I > /home/dbannon/logs/water.log
